### PR TITLE
Corrected order of AUTH and SELECT on connecting

### LINKED ISSUE #53: Wrong order of SELECT and AUTH connection event handlers
Using v0.3.3 when a connection is being created the order of event handlers is wrong.
Currently, it sends `SELECT` and gets `-NOAUTH Authentication required.` this is because `AUTH` is being sent after `SELECT` and should be sent before.
The second thing is if I get an error like `-NOAUTH` would like to know about that with a proper exception thrown.

### PR DESCRIPTION
**Pull request by brzuchal**
Fixes #53 also adds proper unit tests.

### CODE REVIEW

File: lib/Client.php [hunk 1]
```diff
@@ -54,21 +54,21 @@ public function __construct(string $uri) {
             }
         });
 
-        if ($this->database !== 0) {
+        if (!empty($this->password)) {
```
Comment (kelunik) [inline lib/Client.php]: This shouldn't use `empty`, but that's unrelated to the PR.

**Comment by kelunik** [comment]
I think my thought was that the Deferreds are in the correct order with `unshift` then, but they're anyway just dummy values.

**Comment by kelunik** [comment]
Thanks!
